[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
RAILWAY_ENVIRONMENT = "production"
RAILWAY_PUBLIC_DOMAIN = "https://dacar.up.railway.app"
MYSQLHOST = "${{ Railway.MYSQL_HOST }}"
MYSQLPORT = "${{ Railway.MYSQL_PORT }}"
MYSQLDATABASE = "terancar"
MYSQLUSER = "${{ Railway.MYSQL_USERNAME }}"
MYSQLPASSWORD = "${{ Railway.MYSQL_PASSWORD }}" 